/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#2e1500",
        "surface-container-low": "#f5f3ee",
        "surface-dim": "#dbdad5",
        "tertiary-fixed-dim": "#ffb77b",
        "secondary-fixed": "#ffdbd0",
        "tertiary-container": "#5d3000",
        "primary-container": "#1b4332",
        "tertiary-fixed": "#ffdcc2",
        surface: "#fbf9f4",
        "on-primary-fixed": "#002114",
        "primary-fixed-dim": "#a5d0b9",
        "on-primary-fixed-variant": "#274e3d",
        "inverse-on-surface": "#f2f1ec",
        "on-secondary-container": "#795950",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#eae8e3",
        "on-surface-variant": "#414844",
        "on-surface": "#1b1c19",
        "on-tertiary-fixed-variant": "#6d3a00",
        "on-primary": "#ffffff",
        "surface-variant": "#e4e2dd",
        outline: "#717973",
        "on-error": "#ffffff",
        background: "#fbf9f4",
        "on-background": "#1b1c19",
        error: "#ba1a1a",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "surface-bright": "#fbf9f4",
        "secondary-container": "#fed3c7",
        tertiary: "#3d1e00",
        "on-tertiary-container": "#f78a00",
        "on-primary-container": "#86af99",
        "on-secondary": "#ffffff",
        "primary-fixed": "#c1ecd4",
        "surface-tint": "#3f6653",
        "inverse-primary": "#a5d0b9",
        "outline-variant": "#c1c8c2",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#e7bdb1",
        "on-secondary-fixed-variant": "#5d4037",
        "surface-container": "#f0eee9",
        "on-secondary-fixed": "#2c160e",
        secondary: "#77574d",
        "surface-container-highest": "#e4e2dd",
        primary: "#012d1d",
        "inverse-surface": "#30312e",
        "success-container": "#dcfce7",
        "on-success-container": "#166534",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "32px",
        base: "4px",
        "margin-mobile": "16px",
        "max-width": "1280px",
        xs: "4px",
        sm: "8px",
        lg: "24px",
        gutter: "16px",
        md: "16px",
        "margin-desktop": "48px",
      },
      fontFamily: {
        "display-lg": ["var(--font-literata)"],
        "body-md": ["var(--font-be-vietnam)"],
        "headline-lg": ["var(--font-literata)"],
        "headline-lg-mobile": ["var(--font-literata)"],
        "label-md": ["var(--font-be-vietnam)"],
        "headline-md": ["var(--font-literata)"],
        "body-lg": ["var(--font-be-vietnam)"],
        "label-sm": ["var(--font-be-vietnam)"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
